// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZWDJZd2Ncy1m0fH4lPoUKaKr5Q_SzEXI',
    appId: '1:13990665285:web:1a9b213bad4312b568d72c',
    messagingSenderId: '13990665285',
    projectId: 'app1-5c466',
    authDomain: 'app1-5c466.firebaseapp.com',
    storageBucket: 'app1-5c466.appspot.com',
    measurementId: 'G-2VE7EZRB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8T9VVO5oUBKutYc5qCKb0bRy3cObr2FM',
    appId: '1:13990665285:android:9f79baf8b81b4ff568d72c',
    messagingSenderId: '13990665285',
    projectId: 'app1-5c466',
    storageBucket: 'app1-5c466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtCyW-gQNb0VI5EyyOIVCH6zpzlFq7Jwo',
    appId: '1:13990665285:ios:d6bbbc4c18bed38b68d72c',
    messagingSenderId: '13990665285',
    projectId: 'app1-5c466',
    storageBucket: 'app1-5c466.appspot.com',
    iosClientId: '13990665285-dud4nsc7750hfdrj1lf2irrd5ic0dsfj.apps.googleusercontent.com',
    iosBundleId: 'com.shopapp1.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtCyW-gQNb0VI5EyyOIVCH6zpzlFq7Jwo',
    appId: '1:13990665285:ios:e52f6e7113e6ee7468d72c',
    messagingSenderId: '13990665285',
    projectId: 'app1-5c466',
    storageBucket: 'app1-5c466.appspot.com',
    iosClientId: '13990665285-8a95tb9h1b0thatac0pru16oun81jph1.apps.googleusercontent.com',
    iosBundleId: 'com.shopapp1.app.RunnerTests',
  );
}
